name: Deploy Hugo to Pages
on:
  push:
    branches: [master]
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.160.1'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        run: |
          cd public
          git init
          git add -A
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Deploy Hugo site"
          git push --force "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git" master:gh-pages
